# Generated by Django 3.2.6 on 2021-08-11 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favamealapi', '0003_restaurant_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='customer',
        ),
    ]
