# Generated by Django 3.2.6 on 2021-08-11 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favamealapi', '0004_remove_restaurant_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='favorite',
            field=models.ManyToManyField(related_name='favorite', through='favamealapi.FavoriteRestaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
