# Generated by Django 3.2.6 on 2021-08-11 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favamealapi', '0005_restaurant_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='favorite',
            field=models.ManyToManyField(related_name='favoritemeal', through='favamealapi.FavoriteMeal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='favorite',
            field=models.ManyToManyField(related_name='favoriterestaurant', through='favamealapi.FavoriteRestaurant', to=settings.AUTH_USER_MODEL),
        ),
    ]
